### ISSUE TITLE
Background and details

### ISSUE THREAD

**Issue by j3k0** [j3k0/ganomede-events#1]
You should start by forking this: https://github.com/j3k0/ganomede-boilerplate
then replace the README.md with the one from this repo.

There's an implementation of the long polling feature (required also for this module) on another module here: https://github.com/j3k0/ganomede-notifications/tree/master/src/notifications-api

It's in coffeescript, but it's very easy to convert to javascript. (because that's what coffeescript does)...

Please take some time to look at different `ganomede-*` modules so you stay as consistent as possible with the way we've built things so far ([list here](https://github.com/j3k0?utf8=%E2%9C%93&tab=repositories&q=ganomede&type=&language=javascript)). In particular, try to stick with the technology stack if possible...

**Comment by j3k0** [comment]
Hey @leon-valencia 

Anything I can do to help you get started? Maybe split the work into smaller batches?

Please let me know how this is going.

**Comment by engr-lynx** [comment]
Hi @j3k0 

I already started last week on learning the boilerplate (i.e. using the framework) as well as looking through some of the modules. I logged those hours. But, it took me a while to learn and get used to them so I did some offline learning on my own time. I'll apply those starting today as soon as I'm off the road. So, I'll do some extra work for the next 2 days as I'm completely free to work on this. Barring some unforeseen coding difficulties, I should have something for review by Monday morning.

Thanks,
Leon

**Comment by j3k0** [comment]
Okay looking forward to it. Don't hesitate to ask questions, even for small doubts or decisions, I'm always here to help and I try to answer promptly (when I'm online, which I generally am).

**Comment by j3k0** [comment]
Hey. So, what are you working on? Anything blocking?

**Comment by engr-lynx** [comment]
Hi Jean. I'm finishing up the unit tests along with the interface of the router (i.e. dummy data and no redis yet). Next item would be to use redis.
Nothing blocking. Although there is an issue with using SuperTest + Mocha: request timeout is not working. So, I don't have any tests yet for the case where a GET is done on a channel without new events.

**Comment by j3k0** [comment]
Is it because mocha's test timeouts first? I think mocha considers a test to fail if it takes more than 2 seconds... I'm blindly guessing, but if that's the case maybe you can add a way to change the default 30 seconds timeout of the GET request to something shorter (like 0.1 seconds) when running in test mode?

**Comment by engr-lynx** [comment]
No, not that. It's that I can't capture the timeout in supertest. superagent seems to have a .timeout. But when I use that in supertest, the next statement on the chain is ignored. I've also tried checking the err object inside .end in a timeout event by mocha... but it's still a null in that case.

**Comment by engr-lynx** [comment]
Hi. I managed to solve the timeout issue now. (1) In supertest, can't mix .timeout with .expect. My mistake was trying to make code too generic that I was mixing both. (2) It's tricky using .end with .timeout. So, I used promises (.then) instead.
Sorry that took a while. Had to search through superagent's code to resolve this. Anyway, I now have all relevant test cases. I committed them along with the simulated router.
What's missing: (1) polling & (2) Redis

**Comment by j3k0** [comment]
For polling, please check this out:

https://github.com/j3k0/ganomede-notifications/blob/master/src/notifications-api/index.coffee#L94-L105

It's polling already implemented as a middleware (there's a utility class behind that you can just reuse as-is I believe -- just convert it to plain javascript)

**Comment by j3k0** [comment]
How is it going? Close to finish?

**Comment by engr-lynx** [comment]
Almost done. Already finished integrating with Redis. In the middle of
debugging an issue with polling. I'll commit the Redis part as soon as I'm
home later today. As for the polling, I have the full next 2 days to debug
the issue. Thanks.

**Comment by j3k0** [comment]
Can you commit and push the work-in-progress from time to time so we can review and comment. At least once a day is minimal...

**Comment by engr-lynx** [comment]
Notes:
1. The algorithm for filter (used to extract items after a certain ID) in ganomede-notifications assumed that the Redis list would be in order (queue). But it will not be if you run multiple instances of the service and they attempt to insert items simultaneously. Even if async waterfall is used, the order at which the items are inserted (which will be the order of the list) after taking an index using Redis incr may be out of order. In other words, filter will work if you have only one instance of the service doing message insertion. But it will break if you scale up and run multiple instances. So, I've written my own algorithm implemented in redis.store.js.
2. I tried to make everything I've written adhere to functional programming rather than OOP. But, I didn't touch the ones from boilerplate. Having no states and side effects reduces the tendency for bugs to creep in. Plus, functional code is easier to reason about than OOP code.
3. I tried to make the code as flat as possible (not deeply nested) for easier readability and maintainability. Since that also means having multiple intermediate functions, I've made the names as descriptive as possible.
4. I opted to use map rather than loops since they are also more readable, not to mention faster (since the map function is quite optimized).
5. I opted to use Boolean logic and Lambda functions instead of if-then-else statements to avoid assumed conditions and nested conditions (both lead to bugs). This also helps in making lower layer codes more generic since the upper layers will be forced to house the use case specific logic.
6. poll.js, redis.pubsub.js, redis.store.js and utils.js are all generic implementations that may be reused in other services. secret.js, events.store.js, and events.router.js are the layers that utilize the former 4 specifically for ganomede-events.

**Comment by engr-lynx** [comment]
7. All of the above also helped to achieve low coupling and high cohesion of the different modules. Although, events.router.js and secret.js can still be improved in this aspect.

**Comment by j3k0** [comment]
Hi Leon.

I'm quite proficient and an advocate of Functional Programming and Boolean Logic myself, you're not writing FP code just by replacing `if/else` with `&&` and `||`. Your code is just as full of side-effect as any code, from top-level code to bottom-layers.... which is ok, but you cannot claim it's FP.

Moreover, it was very hard to read and understand. There's quite a few bad practices, obvious bugs lying around and a margin of improvement in your javascript, nodeJS, redis skills...

I spent a few hours of cleaning. If you wanna focus on a single file, you can check differences between [events.store.js@master](https://github.com/j3k0/ganomede-events/blob/master/src/events.store.js) and [events.store.js@2219a68f](https://github.com/j3k0/ganomede-events/blob/2219a68f0ad03fd4d10a7266332b660a95c042ce/src/events.store.js) to judge if cleaning doesn't indeed help:

 - easier reading, by minimizing the need scroll around the page
 - decoupling, removing dependency of this module over redis itself
 - bugs, 3 bugs solved -- 2 instances were the callback could have been called twice, 1 were fields that are not part of an event could have be saved in itemStore.
 - removed side effects, for instance of the transformEvent function (now called itemFactory).

Feel free to check other files too. I'm not claiming my code is perfect, but it's the direction I'd like you to go to. Also, you didn't comply to the code formatting standard (`npm lint` should pass).

Would you be willing to write source code like what is now in the master branch in the future?
