### ISSUE TITLE
Implement the javascript client library.

### ISSUE THREAD

**Issue by j3k0** [j3k0/ganomede-events#3]
As specified in README.md, or suggest a better interface.

**Comment by elmigranto** [comment]
Probably just inherit [`EventEmitter`](https://nodejs.org/dist/latest-v7.x/docs/api/events.html) which is a standard Node API for such things (`addListener`, `removeListener`, etc. instead of `on` / `off`, though, there is `#on()` shortcut method).

I see there is a something like subscribtion masks going on, so

  - `*` means everything received;
  - `<service>` means everything received from that service;
  - `<service>:<event-type>` means events of that type received from that server.

**Comment by j3k0** [comment]
Agreed, this makes sense.

**Comment by j3k0** [comment]
Thinking of our own use cases, only using `service:event-type` would make sense.

In term of backend equivalent, we can set `channel` to be equal to ``${from}:${type}``.

**Comment by elmigranto** [comment]
> Probably just inherit [`EventEmitter`](https://nodejs.org/dist/latest-v7.x/docs/api/events.html) 

Also I noticed same can be done for `redis.pubsub` — no need to implement `addHandler` / `removeHandler`.

**Comment by elmigranto** [comment]
About masks, just realized we can't really listen for all events right now, since we only have channels? Maybe we can implement `*` channel in server, if that's really necessary. Also not sure if we need to make channel for each `service:eventType` combination, those could be filtered on client.

This way we won't need to change current server code.

**Comment by j3k0** [comment]
Yes. Server-side `*` channel can be added (later)... then basically server will emit all incoming events to this channel.

About making a channel for each `"service:type"`, I'm not sure why this requires server code change. Also, this is a minor tweak easy to change... We'll see what's best between sending too much useless events to events' listeners, or using more channels (which means clients might have to listen to more channels simultaneously, if they're interested by more that 1 event type).

Do you think you can have the lib delivered soon? There'll be 2 workers to implement when it is ready.

**Comment by elmigranto** [comment]
> About making a channel for each `"service:type"`, I'm not sure why this requires server code change.

At the very minimum, this means multiple publishes per event.

> *useless events* vs *more channels*…

Depends on number of event kinds and worker's scope. If they mostly will need single event kind from single service, than sure, let's do more channles. I guess we can always listen on the `service:*`, so I guess more channels is better.

> Soon?

Yeah :)
Let's aim mid-week, depends on what workers would be.

**Comment by elmigranto** [comment]
http://npmjs.com/package/ganomede-events 🎉

**Comment by j3k0** [comment]
Kewl 🍾
