### ISSUE TITLE
Job queues in general

### ISSUE THREAD

**Issue by elmigranto** [j3k0/ganomede-events#5]
So I understand this module is something like a job queue for worker processess. I remember you mentioned `mailchimp` worker as example that would react to account creation events, retreive user's email and add it to mailing list.

Wouldn't we need to implement pulling jobs from `events` module as well as pushing them to the client. On starting a worker, we'll have:

  - remember last id we processed, fecth all jobs since then, queue them;
  - listen for new ones, when received: update last id processed, queue them.

If we run multiple workers, we'll either have to worry about syncing which one receives a job, or make operations idempotent and sometimes do work twice (that's not too bad, though).

Also, do we want any feedback on job results. Failing to add user to mailing list doesn't sound that critical of a operation, but some other workers might be important enough to the point where we'd like to have a history of their actions. 

So my questions is what are we gaining over just polling some database periodically on worker (which is basically what's happening anyways, but with long poll inbetween polls instead of timeout). I guess that's what we have in the end, except DB is hidden behind HTTP service, which makes this issue somewhat pointless ha-ha, but let's write it down anyway so we are on the same page :)

**Comment by j3k0** [comment]
It's not really a job queue... but a global log of events happening in the system, to allow externalizing implementation of certain features.

All questions concerning job handling is out of scope for this module.

A single event can be used by workers doing different things, or no worker at all...

For instance event "user registers" might be interesting for a mailchimp worker, and also for another worker that reward new users from Germany with some virtual currency...

If we ever need multiple workers that do the same thing (for perfs), we'll need some other means to allocate jobs. Probably only 1 instance will listen for events and fill in a job queue, multiple instance will process the job queue. But this is probably not needed.

Concerning remember the last read ID, we could add to this module a way to do it... An idea: instead of sending the `after` parameter, the caller could provide a `clientID` string &rArr; then events server will pull the value for `after` associated with the provided `clientID` (from redis), and update its value after sending the response.

Clients have to agree on allocating themselves unique IDs, this should be easy (use the GitHub project name, it is unique).

Did I cover all your questions and made stuff clearer?

**Comment by elmigranto** [comment]
All right, makes sense. I like `clientID` idea.

**Comment by elmigranto** [comment]
Let's say we do the following when client asks for "new" events (instead of `after` it sends its `clientID`):

  - server fetches `clients:<clientId>:<channel>` counter storing last event sent to that client from a channel;
  - server sets `after` to w/ever it fetched (or `0`);
  - server fetches events (or waits for them);
  - server updates counter to be last event ID;
  - `res.json()`.

Let's say client receives a bunch of events with IDs `[10, 11, 12]`. Processing event 10 fails, 11 and 12 complete fine (or any other combination of things). Server now has `12` as last event sent. I guess the retrying part is on the client, as well as saving any state it needs, if any. And server's job is only figuring "new" part.

**Comment by elmigranto** [comment]
I find it helpful to think in "`git` terms". Server is basically interface to the `.git/` folder. Client might (or might not) need a "working copy" with some kind of derived data — be it list of events processed, or results of each task.

With `clientID` we remove the need for each client to remember which events are "new" from its perspective, but risk loosing stuff (like client crashed on processing, but server still updated "new" marker).

**Comment by j3k0** [comment]
The `clientID` adds some risk of loosing stuff. We can mitigate this risk by keeping the `after` in memory in the worker (no storage). Then send both `after` and `clientID` in GET requests. The server will use provided `after` in priority (if > 0), and update `clients:<clientId>:<channel>` counter as usual.

Then we might loose stuff only if the worker didn't process an event and crashes... this has to be rare enough.

**Comment by elmigranto** [comment]
Well, if it proccessed event successfully and/or didn't crash, doesn't really matter if we keep `after`, `new` marker would be the same for client and server :)

But yeah, makes sense to not drop `after` and make it have higher priority, so we can "resync" or page events. So server should pick first: explicit `after` on request; counter from its db; 0.
