### ISSUE TITLE
Implement `clientID`

### ISSUE THREAD

**Issue by j3k0** [j3k0/ganomede-events#7]
See #6 for discussion about it.

Instead of (or alongside) the `after` parameter, in GET events requests, the client can specify `clientID`, a string.

Server will read in Redis what was the last sent event for key `<channel>:<clientID>`, use this value for `after` (in case `after` wasn't specified).

After sending the events to the client, value for `<channel>:<clientID>` will be updated.

#6 contains more details. See also API.md for details after `after`, don't forget to document `clientID` in the API.md document.

**Comment by elmigranto** [comment]
What about allowing client to `ack` messages instead of automatically overwriting counter?

  - client: `GET /stuff` channel
  - server: sends ids `[1, 2, 3]`
  - client receives, processes, and sends `GET /ack/3`
  - server overwrites counter to 3 (or we keep a list and `GET /ack/1,2,3` — meh, might not be in order; set?)

With just overwriting on server, we mostly remove the client's need for manual paging with `after`. Messages are still dropped in case of a crash.

**Comment by j3k0** [comment]
Hey sorry, for long feedback on all issues, internet was down in my region yesterday.

Typical client behavior will be:

1. Client `GET /events?clientID=bob&after=X`
2. Server returns events `[X .. Y]`
3. Client process events `X` to `Y`
4. Client `GET /events?clientID=bob&after=Y`
5. etc.

Adding a `ack` for `Y` between 3 and 4 might be unnecessary, the next GET can be considered a ack for Y.

So maybe we should only update `after` according to `clientID` when GET request is received, and do nothing when request is responded to.

Only when `after` is not set, we load it using `clientID`.

**Comment by elmigranto** [comment]
Added this as part of #10.
